// All public Guide Line copy lives here. No account or tournament data is loaded.
const list=items=>`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
const steps=items=>`<ol class="guide-steps">${items.map(item=>`<li>${item}</li>`).join('')}</ol>`;
const flow=items=>`<ol class="guide-flow">${items.map(item=>`<li>${item}</li>`).join('')}</ol>`;
const callout=(title,text)=>`<aside class="guide-callout"><strong>${title}</strong><p>${text}</p></aside>`;
const workflow=['TẠO GIẢI','VĐV / ĐỘI','CHIA BẢNG','TRỌNG TÀI','VÒNG BẢNG','BXH','KNOCKOUT','VINH DANH'];
const sections=[
  {id:'overview',title:'Tổng quan',body:`<p>Pantry Tournament là hệ thống quản lý và vận hành giải Pickleball từ lúc tạo giải đến khi kết thúc.</p><div class="guide-workflow" aria-label="Quy trình chính">${workflow.map((item,i)=>`${i?'<span aria-hidden="true">→</span>':''}<b>${item}</b>`).join('')}</div>${list(['Thông tin giải & poster · nhiều nội dung thi đấu','VĐV / đội · chia bảng · lịch thi đấu · phân sân','Trọng tài điện tử · nhập tỷ số · BXH tự động','LIVE · Knockout · vinh danh','Trang công khai · chia sẻ giải/trận · hành trình đội','Guest Organizer — tài khoản cho ban tổ chức bên ngoài'])}${callout('TRỌNG TÀI ĐIỆN TỬ','Chấm điểm trực tiếp tại sân, không cần phiếu giấy.')}`},
  {id:'create',title:'Tạo giải',body:`${steps(['Chọn <b>+ TẠO GIẢI</b>.','Nhập tên giải, ngày / giờ và các thông tin tạo giải.','Lưu để giải xuất hiện trong hệ thống. Sau đó mở <b>Thông tin giải</b> để bổ sung nội dung công khai.'])}<div class="guide-feature-grid"><div><h3>Thông tin cơ bản</h3>${list(['Tên giải','Ngày / giờ','Poster'])}</div><div><h3>Thông tin công khai</h3>${list(['Thông tin giải','Điều lệ','Giải thưởng','Link đăng ký'])}</div></div>`},
  {id:'events',title:'Nội dung thi đấu',body:`<p>Một giải có thể có một hoặc nhiều nội dung thi đấu. Chọn đúng nội dung trước khi vận hành.</p><div class="guide-tags"><span>Đôi nam 5.0</span><span>Đôi nam nữ 4.8</span><span>Đôi nữ 4.5</span><span>Newbie</span></div><p>Mỗi nội dung có đội, bảng, trận đấu, BXH, Knockout và kết quả riêng.</p>`},
  {id:'teams',title:'VĐV / Đội',body:`<p>Mở tab <b>VĐV / ĐỘI</b> để quản lý danh sách thi đấu.</p>${steps(['Nhập đội / VĐV bằng tay hoặc chọn import từ Excel.','Dùng cấu trúc danh sách phù hợp với nội dung <b>Đánh đôi</b> hoặc <b>MLP</b> đang sử dụng.','Kiểm tra tên đội và thành viên trước khi chia bảng.'])}<p>Đánh đôi sử dụng cặp VĐV. MLP sử dụng đội và các vị trí thành viên theo cấu hình hiện có.</p>`},
  {id:'groups',title:'Chia bảng',body:`${steps(['Mở <b>CHIA BẢNG</b>.','Chọn số lượng bảng.','Hệ thống phân bổ đội và tạo các trận vòng tròn (Round Robin).'])}${callout('VÍ DỤ','24 đội → 6 bảng → 4 đội/bảng.')}<p>Có thể xáo trộn bốc thăm / thứ tự trước khi thi đấu ở những thao tác hệ thống hỗ trợ. Kiểm tra lại bảng và lịch trận trước khi bắt đầu.</p>`},
  {id:'matches',title:'Trận đấu',body:`<p>Mỗi trận hiển thị mã trận, đội 1, đội 2, tỷ số, trạng thái, sân và thông tin LIVE khi có.</p><h3>Nhập tỷ số tại bàn điều hành</h3><p>Admin / Staff dùng ô điểm của trận:</p><div class="guide-example"><b>Điểm đội 1 : Điểm đội 2</b><span>→ LƯU TỈ SỐ</span></div><p>BXH cập nhật từ kết quả đã lưu. Guest Organizer được vận hành trong các giải có quyền quản lý.</p>`},
  {id:'courts',title:'Phân sân',body:`<p>Admin / Staff chọn sân cho từng trận trong màn hình vận hành. Guest Organizer thao tác trong giải được cấp quyền.</p><div class="guide-tags"><span>Sân 1</span><span>Sân 2</span><span>Sân 3…</span></div><p>Thông tin sân hiển thị cùng trận đấu. Hệ thống ngăn các trận đang thi đấu sử dụng trùng sân trong phạm vi bảo vệ sân hiện có.</p>`},
  {id:'referee',title:'Trọng tài điện tử',featured:true,body:`<h3 class="guide-feature-title">TRỌNG TÀI ĐIỆN TỬ</h3><p class="guide-lead">Không cần phiếu điểm giấy.</p><div class="guide-feature-grid"><div><h3>Quy trình truyền thống</h3><p>BTC in phiếu → giao trọng tài → trọng tài ghi tay → kết thúc trận → mang phiếu về bàn chính → BTC nhập lại kết quả → BXH mới cập nhật.</p></div><div><h3>Với Pantry Tournament</h3><p><b>TRỌNG TÀI MỞ ĐIỆN THOẠI</b> → chọn trận → chấm điểm trực tiếp → kết thúc trận → kết quả & BXH cập nhật ngay.</p></div></div><h3>Vào bàn trọng tài</h3>${steps(['Chọn <b>TÔI LÀ TRỌNG TÀI</b> trên trang giải.','Nhập tên trọng tài.','Chọn bảng / phạm vi được phân công.','Nhập mã truy cập do BTC cấp.','Chọn trận.','Bấm <b>BẮT ĐẦU TRẬN</b>.'])}<h3>Chấm điểm ngay trên điện thoại</h3><p>Dùng nút <b>+</b> / <b>−</b> để tăng hoặc giảm điểm. Chọn đích điểm phù hợp như chạm 11, chạm 15 hoặc đích tùy chỉnh khi hệ thống hỗ trợ. Khi đủ điều kiện kết thúc, bấm <b>KẾT THÚC TRẬN</b> và xác nhận để gửi kết quả trực tiếp về hệ thống.</p>${callout('KHÔNG CẦN MANG PHIẾU ĐIỂM VỀ BÀN TRỌNG TÀI CHÍNH.','Kết quả được chuyển từ sân về hệ thống, giúp BTC theo dõi giải theo thời gian thực.')}<div class="guide-feature-grid"><div><h3>Các bước tại sân</h3>${flow(['TÔI LÀ TRỌNG TÀI','NHẬP TÊN + MÃ TRUY CẬP','CHỌN BẢNG','CHỌN TRẬN','BẮT ĐẦU TRẬN','CHẤM ĐIỂM + / −','KẾT THÚC TRẬN','KẾT QUẢ & BXH CẬP NHẬT'])}</div><div><h3>Lợi ích cho BTC</h3>${list(['Không cần in phiếu','Không thất lạc phiếu','Không nhập tỷ số hai lần','Giảm sai sót','BXH cập nhật nhanh','Nhiều trọng tài có thể làm việc đồng thời','BTC theo dõi giải theo thời gian thực'])}<p><b>Phạm vi riêng:</b> trọng tài chỉ chấm các trận thuộc phạm vi được phân công, không nhận quyền Admin toàn hệ thống.</p></div></div>`},
  {id:'standings',title:'BXH',body:`<p>BXH được tính từ kết quả vòng bảng đã lưu.</p><dl class="guide-definitions"><div><dt>Trận</dt><dd>Số trận đã có kết quả.</dd></div><div><dt>Thắng / Thua</dt><dd>Số trận thắng và số trận thua của đội.</dd></div><div><dt>Hiệu số</dt><dd>Chênh lệch điểm ghi được và điểm bị ghi.</dd></div></dl><p>BXH cũng là cơ sở xác định các đội đi tiếp vào Knockout.</p>`},
  {id:'live',title:'LIVE',featured:true,body:`${callout('BẬT LIVE','Trận đủ điều kiện có nút BẬT LIVE để mở luồng phát cho chính trận đó.')}${flow(['BẬT LIVE','MỞ QR','ĐIỆN THOẠI QUÉT QR','CHO PHÉP CAMERA / MICROPHONE','PHÁT TRỰC TIẾP'])}<p>Khán giả chọn <b>🔴 XEM LIVE</b> khi trận đang phát. LIVE gắn với từng trận cụ thể và sử dụng được cho cả <b>vòng bảng</b> lẫn <b>Knockout</b> đủ điều kiện.</p>`},
  {id:'knockout',title:'Knockout',featured:true,body:`<p>Sau khi vòng bảng hoàn tất, mở <b>KNOCKOUT → XEM TRƯỚC KNOCKOUT TỪ BXH</b>. Kiểm tra danh sách đi tiếp và nhánh trước khi xác nhận tạo.</p><h3>Suất đi tiếp theo số bảng</h3><dl class="guide-qualification"><div><dt>8 bảng</dt><dd>Nhất + Nhì → 16 đội.</dd></div><div><dt>7 bảng</dt><dd>Nhất + Nhì + 2 đội hạng 3 tốt nhất → 16 đội.</dd></div><div><dt>6 bảng</dt><dd>Nhất + Nhì + 4 đội hạng 3 tốt nhất → 16 đội.</dd></div><div><dt>5 bảng</dt><dd>5 Nhất bảng vào thẳng Tứ kết. 5 Nhì bảng + 1 đội hạng 3 tốt nhất đấu Playoff. 3 đội thắng Playoff + 5 Nhất bảng → Tứ kết.</dd></div><div><dt>4 bảng</dt><dd>Nhất + Nhì → Tứ kết.</dd></div></dl><h3>Tiến trình nhánh</h3><p class="guide-route">1/16 → TỨ KẾT → BÁN KẾT → CHUNG KẾT</p><p class="guide-route">PLAYOFF → TỨ KẾT → BÁN KẾT → CHUNG KẾT</p><p>Cách xếp nhánh cố gắng hạn chế các đội cùng bảng gặp lại quá sớm. Ô chưa xác định đội có thể hiển thị <b>Thắng R16-1</b> hoặc <b>Thắng QF-1</b>.</p><h3>Nhập tỷ số Knockout</h3><p>Khi cả hai đội đã được xác định, nhập điểm và bấm <b>LƯU TỈ SỐ</b>. Trận Knockout không được hòa.</p>${steps(['Lưu kết quả trận.','Hệ thống xác định đội thắng và tự chuyển đội vào đúng trận tiếp theo.','Nhánh phía sau cập nhật ngay; khi đủ hai đội, trận tiếp theo có ô nhập điểm.'])}<div class="guide-example"><b>R16-1</b><span>Felix - Jenny <strong>11</strong></span><span>An CXM - An TH <strong>10</strong></span><b>→ Felix - Jenny xuất hiện ở QF.</b></div><p>Các trận Knockout cũng sử dụng tính năng phân sân và LIVE hiện có.</p>`},
  {id:'awards',title:'Vinh danh',body:`<p>Mở <b>VINH DANH</b> để chọn kết quả và lưu thông tin công bố.</p><div class="guide-tags"><span>🥇 Vô địch</span><span>🥈 Á quân</span><span>🥉 Hạng Ba</span></div><p>Nếu nội dung có đồng hạng Ba, có thể chọn hai đội hạng Ba. Kết quả vinh danh hiển thị trên trang công khai.</p>`},
  {id:'public',title:'Trang công khai',body:`<p>Khán giả <b>không cần đăng nhập</b> để theo dõi giải.</p>${list(['Thông tin giải và danh sách đội đăng ký','Bảng đấu, lịch trận, tỷ số và BXH','LIVE, nhánh Knockout và vinh danh'])}<p>Trang công khai chỉ cho phép xem, không cho phép thay đổi dữ liệu giải.</p>`},
  {id:'share',title:'Chia sẻ',body:`<p><b>CHIA SẺ GIẢI</b> chia sẻ trang thông tin giải. Bạn cũng có thể chia sẻ đường dẫn riêng của từng trận.</p><div class="guide-tags"><span>Zalo</span><span>Messenger</span><span>Facebook</span><span>Nhóm VĐV</span></div><p>Gửi link để mọi người theo dõi giải, xem một trận LIVE hoặc mở đúng trận Knockout cần xem.</p>`},
  {id:'journey',title:'Hành trình đội',body:`<p>Chọn một đội trên trang giải để xem hành trình thi đấu của đội đó.</p>${list(['Đối thủ và mã trận','Tỷ số, kết quả / trạng thái','Sân thi đấu','Các vòng Knockout đội đã đi tới'])}<p>Thông tin hiển thị theo dữ liệu và tiến độ thực tế của giải.</p>`},
  {id:'guests',title:'Tài khoản khách',body:`<p>Pantry Admin có thể tạo tài khoản <b>Guest Organizer</b> cho ban tổ chức bên ngoài.</p><div class="guide-feature-grid"><div><h3>A. GIẢI TỰ TẠO</h3><p>Khi được cho phép tự tạo giải, Guest Organizer có thể tạo và vận hành các giải của mình.</p></div><div><h3>B. GIẢI ĐƯỢC CHỈ ĐỊNH</h3><p>Pantry Admin có thể gán các giải hiện có để Guest Organizer vận hành.</p></div></div><p><b>Hai nguồn quyền hoạt động đồng thời.</b> Guest Organizer chỉ quản lý giải mình sở hữu hoặc được Admin chỉ định.</p><h3>Ngày hết hạn và gia hạn</h3><p>Mỗi tài khoản có ngày giờ hết hạn. Khi hết hạn, quyền vận hành dừng nhưng dữ liệu giải vẫn được giữ nguyên. Admin có thể gia hạn để khôi phục quyền truy cập.</p><div class="guide-tags"><span>GIA HẠN</span><span>GÁN GIẢI</span><span>QUẢN LÝ QUYỀN</span><span>KHÓA ACCOUNT</span></div>`},
  {id:'roles',title:'Phân quyền',body:`<dl class="guide-definitions"><div><dt>ADMIN</dt><dd>Toàn quyền quản lý hệ thống.</dd></div><div><dt>STAFF</dt><dd>Các quyền vận hành hiện có của Staff.</dd></div><div><dt>GUEST ORGANIZER</dt><dd>Chỉ quản lý giải tự sở hữu và giải được chỉ định, trong thời hạn tài khoản còn hiệu lực.</dd></div><div><dt>REFEREE</dt><dd>Chấm điểm trong phạm vi trọng tài được phân công.</dd></div><div><dt>PUBLIC</dt><dd>Khán giả chỉ xem thông tin công khai.</dd></div></dl>`},
  {id:'workflow',title:'Quy trình vận hành',body:`<p>Checklist từ lúc chuẩn bị đến khi công bố kết quả giải.</p>${flow(['01 — TẠO GIẢI','02 — TẠO NỘI DUNG','03 — THÊM / IMPORT VĐV','04 — CHIA BẢNG','05 — KIỂM TRA LỊCH TRẬN','06 — PHÂN SÂN','07 — CẤP MÃ CHO TRỌNG TÀI','08 — TRỌNG TÀI CHẤM ĐIỂM TẠI SÂN','09 — KẾT QUẢ & BXH TỰ CẬP NHẬT','10 — BẬT LIVE NẾU CẦN','11 — TẠO KNOCKOUT TỪ BXH','12 — THI ĐẤU KNOCKOUT','13 — CHUNG KẾT','14 — VINH DANH'])}`}
];

export function openGuideLine(){
  if(document.querySelector('.guide-dialog'))return;
  const previousFocus=document.activeElement,previousOverflow=document.body.style.overflow;
  const dialog=document.createElement('dialog');dialog.className='guide-dialog';
  dialog.setAttribute('aria-labelledby','guide-title');dialog.setAttribute('aria-describedby','guide-subtitle');
  dialog.innerHTML=`<div class="guide-shell"><div class="guide-header"><div><h2 id="guide-title">GUIDE LINE</h2><p id="guide-subtitle">Hướng dẫn sử dụng Pantry Tournament</p></div><button type="button" class="guide-close" aria-label="Đóng hướng dẫn" autofocus>×</button></div><div class="guide-layout"><nav class="guide-nav" aria-label="Mục lục hướng dẫn">${sections.map((s,i)=>`<button type="button" data-guide-section="${s.id}" ${i===0?'aria-current="location"':''}><span>${String(i+1).padStart(2,'0')}.</span> ${s.title}</button>`).join('')}</nav><label class="guide-selector">Chọn mục<select>${sections.map((s,i)=>`<option value="${s.id}">${String(i+1).padStart(2,'0')}. ${s.title}</option>`).join('')}</select></label><div class="guide-content" tabindex="0" role="region" aria-label="Nội dung hướng dẫn">${sections.map((s,i)=>`<section id="guide-${s.id}" class="guide-section ${s.featured?'guide-section-featured':''}" aria-labelledby="guide-heading-${s.id}"><div class="guide-section-title"><span>${String(i+1).padStart(2,'0')}</span><h2 id="guide-heading-${s.id}">${s.title}</h2></div>${s.body}</section>`).join('')}<p class="guide-end">THE PANTRY · TOURNAMENT</p></div></div></div>`;
  document.body.append(dialog);document.body.style.overflow='hidden';dialog.showModal();
  const content=dialog.querySelector('.guide-content'),selector=dialog.querySelector('select');
  const nodes=[...dialog.querySelectorAll('.guide-section')];
  const activate=id=>{
    selector.value=id;
    dialog.querySelectorAll('[data-guide-section]').forEach(button=>{
      if(button.dataset.guideSection===id)button.setAttribute('aria-current','location');else button.removeAttribute('aria-current');
    });
  };
  const navigate=id=>{
    const section=dialog.querySelector(`#guide-${id}`);
    content.scrollTo({top:content.scrollTop+section.getBoundingClientRect().top-content.getBoundingClientRect().top-20,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
    activate(id);
  };
  dialog.querySelectorAll('[data-guide-section]').forEach(button=>button.onclick=()=>navigate(button.dataset.guideSection));
  selector.onchange=()=>navigate(selector.value);
  content.addEventListener('scroll',()=>{
    const top=content.getBoundingClientRect().top+60;
    const current=nodes.filter(node=>node.getBoundingClientRect().top<=top).at(-1)||nodes[0];
    activate(current.id.slice(6));
  },{passive:true});
  dialog.querySelector('.guide-close').onclick=()=>dialog.close();
  dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
  dialog.addEventListener('close',()=>{
    document.body.style.overflow=previousOverflow;dialog.remove();
    (previousFocus?.isConnected?previousFocus:document.querySelector('#guideLineButton'))?.focus();
  },{once:true});
}
