-- Pantry Tournament — Referee Mode migration
-- Safe to run once. Adds scoped referee access without requiring a Supabase user account.

begin;

create table if not exists public.referee_access_codes (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  code_hash text not null,
  active boolean not null default true,
  expires_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, group_id)
);

create table if not exists public.referee_sessions (
  id uuid primary key default gen_random_uuid(),
  access_code_id uuid not null references public.referee_access_codes(id) on delete cascade,
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  referee_name text not null,
  active boolean not null default true,
  expires_at timestamptz not null default (now() + interval '12 hours'),
  created_at timestamptz not null default now(),
  last_used_at timestamptz not null default now()
);

create table if not exists public.referee_score_logs (
  id bigint generated by default as identity primary key,
  referee_session_id uuid references public.referee_sessions(id) on delete set null,
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  group_id uuid references public.groups(id) on delete set null,
  match_id uuid references public.matches(id) on delete set null,
  referee_name text,
  action text not null,
  old_team1_score integer,
  old_team2_score integer,
  new_team1_score integer,
  new_team2_score integer,
  created_at timestamptz not null default now()
);

create index if not exists referee_sessions_group_idx
  on public.referee_sessions(tournament_id, group_id, active);

create index if not exists referee_score_logs_tournament_idx
  on public.referee_score_logs(tournament_id, created_at desc);

alter table public.referee_access_codes enable row level security;
alter table public.referee_sessions enable row level security;
alter table public.referee_score_logs enable row level security;

drop policy if exists "staff read referee codes" on public.referee_access_codes;
create policy "staff read referee codes"
on public.referee_access_codes for select
to authenticated
using (public.is_staff());

drop policy if exists "staff read referee sessions" on public.referee_sessions;
create policy "staff read referee sessions"
on public.referee_sessions for select
to authenticated
using (public.is_staff());

drop policy if exists "staff update referee sessions" on public.referee_sessions;
create policy "staff update referee sessions"
on public.referee_sessions for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "staff read referee logs" on public.referee_score_logs;
create policy "staff read referee logs"
on public.referee_score_logs for select
to authenticated
using (public.is_staff());

grant select on public.referee_access_codes to authenticated;
grant select, update on public.referee_sessions to authenticated;
grant select on public.referee_score_logs to authenticated;

-- Admin/staff creates or resets one code for one group.
create or replace function public.set_referee_code(
  p_tournament_id uuid,
  p_group_id uuid,
  p_code text,
  p_expires_at timestamptz default null
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_id uuid;
begin
  if auth.uid() is null or not public.is_staff() then
    raise exception 'Staff permission required';
  end if;

  if p_code is null or length(trim(p_code)) < 4 then
    raise exception 'Referee code must contain at least 4 characters';
  end if;

  if not exists (
    select 1 from public.groups g
    where g.id = p_group_id and g.tournament_id = p_tournament_id
  ) then
    raise exception 'Group does not belong to this tournament';
  end if;

  insert into public.referee_access_codes
    (tournament_id, group_id, code_hash, active, expires_at, created_by, updated_at)
  values
    (p_tournament_id, p_group_id, crypt(trim(p_code), gen_salt('bf')), true, p_expires_at, auth.uid(), now())
  on conflict (tournament_id, group_id)
  do update set
    code_hash = excluded.code_hash,
    active = true,
    expires_at = excluded.expires_at,
    created_by = auth.uid(),
    updated_at = now()
  returning id into v_id;

  update public.referee_sessions
  set active = false
  where tournament_id = p_tournament_id
    and group_id = p_group_id;

  return v_id;
end;
$$;

-- Admin/staff revokes the group code and all current referee sessions for that group.
create or replace function public.revoke_referee_code(
  p_tournament_id uuid,
  p_group_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_staff() then
    raise exception 'Staff permission required';
  end if;

  update public.referee_access_codes
  set active = false, updated_at = now()
  where tournament_id = p_tournament_id and group_id = p_group_id;

  update public.referee_sessions
  set active = false
  where tournament_id = p_tournament_id and group_id = p_group_id;
end;
$$;

-- Public referee claims access. The returned UUID is a bearer session token.
create or replace function public.claim_referee_access(
  p_tournament_id uuid,
  p_group_id uuid,
  p_referee_name text,
  p_code text
)
returns table (
  session_token uuid,
  tournament_id uuid,
  group_id uuid,
  group_name text,
  referee_name text,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_code public.referee_access_codes%rowtype;
  v_session public.referee_sessions%rowtype;
  v_group_name text;
begin
  if length(trim(coalesce(p_referee_name,''))) < 2 then
    raise exception 'Please enter referee name';
  end if;

  select *
  into v_code
  from public.referee_access_codes c
  where c.tournament_id = p_tournament_id
    and c.group_id = p_group_id
    and c.active = true
    and (c.expires_at is null or c.expires_at > now())
  limit 1;

  if v_code.id is null
     or crypt(trim(coalesce(p_code,'')), v_code.code_hash) <> v_code.code_hash then
    raise exception 'Invalid referee code';
  end if;

  select g.name into v_group_name
  from public.groups g
  where g.id = p_group_id and g.tournament_id = p_tournament_id;

  if v_group_name is null then
    raise exception 'Invalid group';
  end if;

  insert into public.referee_sessions
    (access_code_id, tournament_id, group_id, referee_name)
  values
    (v_code.id, p_tournament_id, p_group_id, trim(p_referee_name))
  returning * into v_session;

  return query
  select v_session.id, v_session.tournament_id, v_session.group_id,
         v_group_name, v_session.referee_name, v_session.expires_at;
end;
$$;

-- Referee submits/edits a normal doubles or MLP Mini aggregate score.
create or replace function public.referee_submit_score(
  p_session_token uuid,
  p_match_id uuid,
  p_team1_score integer,
  p_team2_score integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.referee_sessions%rowtype;
  v_match public.matches%rowtype;
  v_winner uuid;
begin
  if p_team1_score is null or p_team2_score is null
     or p_team1_score < 0 or p_team2_score < 0
     or p_team1_score = p_team2_score then
    raise exception 'Invalid score';
  end if;

  select * into v_session
  from public.referee_sessions s
  where s.id = p_session_token
    and s.active = true
    and s.expires_at > now();

  if v_session.id is null then
    raise exception 'Referee session expired or revoked';
  end if;

  select * into v_match
  from public.matches m
  where m.id = p_match_id
    and m.tournament_id = v_session.tournament_id
    and m.group_id = v_session.group_id
    and m.stage = 'group';

  if v_match.id is null then
    raise exception 'You do not have permission for this match';
  end if;

  v_winner := case
    when p_team1_score > p_team2_score then v_match.team1_id
    else v_match.team2_id
  end;

  insert into public.referee_score_logs
    (referee_session_id, tournament_id, group_id, match_id, referee_name, action,
     old_team1_score, old_team2_score, new_team1_score, new_team2_score)
  values
    (v_session.id, v_session.tournament_id, v_session.group_id, v_match.id,
     v_session.referee_name,
     case when v_match.status = 'completed' then 'edit_score' else 'submit_score' end,
     v_match.team1_score, v_match.team2_score, p_team1_score, p_team2_score);

  update public.matches
  set team1_score = p_team1_score,
      team2_score = p_team2_score,
      winner_id = v_winner,
      status = 'completed',
      completed_at = now()
  where id = v_match.id;

  update public.referee_sessions
  set last_used_at = now()
  where id = v_session.id;
end;
$$;

-- Referee submits one game for MLP Basic. The server recomputes the match series.
create or replace function public.referee_submit_mlp_game(
  p_session_token uuid,
  p_match_id uuid,
  p_game_order integer,
  p_game_type text,
  p_team1_score integer,
  p_team2_score integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.referee_sessions%rowtype;
  v_match public.matches%rowtype;
  v_game_id uuid;
  v_game_winner uuid;
  v_a4 integer := 0;
  v_b4 integer := 0;
  v_w1 integer := 0;
  v_w2 integer := 0;
  v_db_winner uuid;
  v_completed boolean := false;
  v_match_winner uuid := null;
begin
  if p_game_order not between 1 and 5 then
    raise exception 'Invalid MLP game';
  end if;

  if p_team1_score is null or p_team2_score is null
     or p_team1_score < 0 or p_team2_score < 0
     or p_team1_score = p_team2_score then
    raise exception 'Invalid score';
  end if;

  select * into v_session
  from public.referee_sessions s
  where s.id = p_session_token
    and s.active = true
    and s.expires_at > now();

  if v_session.id is null then
    raise exception 'Referee session expired or revoked';
  end if;

  select * into v_match
  from public.matches m
  where m.id = p_match_id
    and m.tournament_id = v_session.tournament_id
    and m.group_id = v_session.group_id
    and m.stage = 'group';

  if v_match.id is null then
    raise exception 'You do not have permission for this match';
  end if;

  v_game_winner := case
    when p_team1_score > p_team2_score then v_match.team1_id
    else v_match.team2_id
  end;

  select id into v_game_id
  from public.mlp_games
  where match_id = p_match_id and game_order = p_game_order
  limit 1;

  if v_game_id is null then
    insert into public.mlp_games
      (match_id, game_order, game_type, team1_score, team2_score, winner_team_id)
    values
      (p_match_id, p_game_order, p_game_type, p_team1_score, p_team2_score, v_game_winner);
  else
    update public.mlp_games
    set game_type = p_game_type,
        team1_score = p_team1_score,
        team2_score = p_team2_score,
        winner_team_id = v_game_winner
    where id = v_game_id;
  end if;

  select
    count(*) filter (where game_order <= 4 and winner_team_id = v_match.team1_id),
    count(*) filter (where game_order <= 4 and winner_team_id = v_match.team2_id)
  into v_a4, v_b4
  from public.mlp_games
  where match_id = p_match_id;

  if (select count(*) from public.mlp_games where match_id=p_match_id and game_order<=4) = 4 then
    if v_a4 <> v_b4 then
      v_completed := true;
      v_match_winner := case when v_a4 > v_b4 then v_match.team1_id else v_match.team2_id end;
      v_w1 := v_a4;
      v_w2 := v_b4;
    else
      select winner_team_id into v_db_winner
      from public.mlp_games
      where match_id = p_match_id and game_order = 5
      limit 1;

      if v_db_winner is not null then
        v_completed := true;
        v_match_winner := v_db_winner;
        v_w1 := v_a4 + case when v_db_winner = v_match.team1_id then 1 else 0 end;
        v_w2 := v_b4 + case when v_db_winner = v_match.team2_id then 1 else 0 end;
      else
        v_w1 := v_a4;
        v_w2 := v_b4;
      end if;
    end if;
  else
    select
      count(*) filter (where winner_team_id = v_match.team1_id),
      count(*) filter (where winner_team_id = v_match.team2_id)
    into v_w1, v_w2
    from public.mlp_games
    where match_id = p_match_id;
  end if;

  update public.matches
  set team1_score = v_w1,
      team2_score = v_w2,
      winner_id = case when v_completed then v_match_winner else null end,
      status = case when v_completed then 'completed' else 'scheduled' end,
      completed_at = case when v_completed then now() else null end
  where id = p_match_id;

  insert into public.referee_score_logs
    (referee_session_id, tournament_id, group_id, match_id, referee_name, action,
     old_team1_score, old_team2_score, new_team1_score, new_team2_score)
  values
    (v_session.id, v_session.tournament_id, v_session.group_id, p_match_id,
     v_session.referee_name, 'mlp_game_' || p_game_order,
     v_match.team1_score, v_match.team2_score, v_w1, v_w2);

  update public.referee_sessions set last_used_at = now() where id = v_session.id;
end;
$$;

revoke all on function public.set_referee_code(uuid,uuid,text,timestamptz) from public;
revoke all on function public.revoke_referee_code(uuid,uuid) from public;
revoke all on function public.claim_referee_access(uuid,uuid,text,text) from public;
revoke all on function public.referee_submit_score(uuid,uuid,integer,integer) from public;
revoke all on function public.referee_submit_mlp_game(uuid,uuid,integer,text,integer,integer) from public;

grant execute on function public.set_referee_code(uuid,uuid,text,timestamptz) to authenticated;
grant execute on function public.revoke_referee_code(uuid,uuid) to authenticated;
grant execute on function public.claim_referee_access(uuid,uuid,text,text) to anon, authenticated;
grant execute on function public.referee_submit_score(uuid,uuid,integer,integer) to anon, authenticated;
grant execute on function public.referee_submit_mlp_game(uuid,uuid,integer,text,integer,integer) to anon, authenticated;

commit;

-- Quick verification:
select
  to_regclass('public.referee_access_codes') as referee_codes,
  to_regclass('public.referee_sessions') as referee_sessions,
  to_regclass('public.referee_score_logs') as referee_logs;
